FROM registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7

ENV BASH_ENV=/usr/local/bin/scl_enable \
    ENV=/usr/local/bin/scl_enable \
    NODEJS_VERSION=8 \
    NPM_CONFIG_PREFIX=$HOME/.npm-global \
    PATH=$HOME/node_modules/.bin/:$HOME/.npm-global/bin/:$PATH \
    PROMPT_COMMAND=". /usr/local/bin/scl_enable" \
    SONAR_RUNNER_HOME=/opt/sonar-runner \
    SONAR_RUNNER_VERSION=2.4 \
    YARN_VERSION=1.15.2

LABEL com.redhat.component="jenkins-agent-nodejs-${NODEJS_VERSION}-sonar${SONAR_RUNNER_VERSION}-rhel7-container" \
      io.k8s.description="The jenkins agent nodejs image has the nodejs tools on top of the jenkins slave base image." \
      io.k8s.display-name="Jenkins Agent - Node.js ${NODEJS_VERSION} - Sonar scanner" \
      io.openshift.tags="openshift,jenkins,agent,nodejs${NODEJS_VERSION},sonar${SONAR_RUNNER_VERSION},nodejs,sonar" \
      architecture="x86_64" \
      name="ci/jenkins-slave-node-${NODEJS_VERSION}-sonar${SONAR_RUNNER_VERSION}" \
      maintainer="Samuel MARTIN MORO <faust64@gmail.com>" \
      help="For more information visit https://github.com/faust64/docker-jenkins-agent-node-sonar" \
      version="${NODEJS_VERSION}"

COPY config/* /usr/local/bin/

# Install NodeJS
RUN if test "$DO_UPGRADE"; then \
	yum -y upgrade; \
    fi \
    && yum-config-manager --enable rhel-server-rhscl-7-rpms \    
    && yum-config-manager --enable rhel-7-server-optional-rpms \
    && yum-config-manager --enable rhel-server-rhscl-8-rpms \ 
    && yum-config-manager --enable rhel-8-server-optional-rpms \
    && ( yum-config-manager --disable epel >/dev/null || true ) \
    && yum install -y --setopt=tsflags=nodocs rh-nodejs${NODEJS_VERSION} \
	rh-nodejs${NODEJS_VERSION}-nodejs-nodemon make gcc-c++ subversion \
	mercurial git wget curl unzip openssh ca-certificates procps-ng bash \
	openssl-devel nss_wrapper \
    && wget -O /usr/src/yarn.tar.gz \
	https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn-v${YARN_VERSION}.tar.gz \
    && tar -C /opt -xzf /usr/src/yarn.tar.gz \
    && rm -f /usr/src/yarn.tar.gz \
    && ln -s /usr/lib/node_modules/nodemon/bin/nodemon.js /usr/bin/nodemon \
    && yum clean all -y \
    && rm -fr /var/cache/yum
ENV PATH=/opt/rh/rh-nodejs8/root/usr/bin:/opt/yarn-v${YARN_VERSION}/bin:$PATH

# Setup NodeJS modules - Fix Java
RUN if test "$HTTP_PROXY"; then \
	( \
	    echo registry=http://registry.npmjs.org/ \
	    && echo http-proxy=$HTTP_PROXY \
	    && echo proxy=$HTTP_PROXY \
	    && echo strict-ssl=false \
	) >$HOME/.npmrc; \
    fi \
    && npm install -g node-gyp pm2 mocha sonar-runner expect \
    && for bin in java jre keytool servertool; \
       do \
           test -x /usr/bin/$bin -o -h /usr/bin/$bin && continue; \
           find /usr/lib/jvm -name $bin | grep $(uname -m) | sort | tail -1 \
	       | while read source; \
	       do \
		   ln -sf $source /usr/bin/$bin; \
	       done; \
       done \
    && rm -f $HOME/.npmrc \
    && if test -s /run/secrets/kubernetes.io/serviceaccount/service-ca.crt; then \
	chmod 0666 /etc/pki/ca-trust/extracted/java/cacerts \
	&& keytool -importcert -alias Root_CA -keystore /etc/pki/ca-trust/extracted/java/cacerts -file /run/secrets/kubernetes.io/serviceaccount/service-ca.crt -storepass changeit --noprompt \
	&& chmod 0444 /etc/pki/ca-trust/extracted/java/cacerts \
	&& cat /run/secrets/kubernetes.io/serviceaccount/service-ca.crt >/etc/pki/ca-trust/source/anchors/k8s-ca.pem \
	&& chmod 0644 /etc/pki/ca-trust/source/anchors/k8s-ca.pem \
	&& update-ca-trust; \
    fi

# Install Sonar Runner
RUN mkdir -p /opt \
    && wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/${SONAR_RUNNER_VERSION}/sonar-runner-dist-${SONAR_RUNNER_VERSION}.zip \
    && unzip sonar-runner-dist-${SONAR_RUNNER_VERSION}.zip \
    && mv sonar-runner-${SONAR_RUNNER_VERSION} /opt/sonar-runner \
    && rm -rf sonar-runner-dist-${SONAR_RUNNER_VERSION}.zip /opt/sonar-runner/conf/sonar-runner.properties \
    && chown -R 1001:0 $HOME $SONAR_RUNNER_HOME \
    && chmod -R g+rw $HOME $SONAR_RUNNER_HOME
ENV PATH $SONAR_RUNNER_HOME/bin:$PATH

USER 1001
