apiVersion: v1
kind: Template
labels:
  app: jenkins-agent-node-sonar
  template: jenkins-agent-node-sonar-buildconfig-with-secret
metadata:
  annotations:
    description: Jenkins Agent NodeJS Sonar Image - BuildConfig with Secret
      see https://github.com/faust64/docker-jenkins-agent-node-sonar
    iconClass: icon-openshift
    openshift.io/display-name: Jenkins Agent NodeJS Sonar
    tags: jenkins-agent-node-sonar
  name: jenkins-agent-node-sonar-buildconfig-with-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-username: "{.data['username']}"
    name: git-jans-${JANS_REPOSITORY_REF}
  stringData:
    username: "${GIT_DEPLOYMENT_TOKEN}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Jenkins Agent NodeJS Sonar images
    labels:
      name: jans-${JANS_REPOSITORY_REF}
    name: jans-${JANS_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 300m
        memory: 1536Mi
    source:
      contextDir: /
      git:
        uri: ${JANS_REPOSITORY_URL}
        ref: "${JANS_REPOSITORY_REF}"
      sourceSecret:
        name: git-jans-${JANS_REPOSITORY_REF}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-node-sonar:${JANS_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: GIT_DEPLOYMENT_TOKEN
  description: Git deployment token
  displayName: Git Deployment Token
  required: true
- name: JANS_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: JANS_REPOSITORY_URL
  description: The URL of the repository with your Jenkins Agent NodeJS Sonar Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/faust64/docker-jenkins-agent-node-sonar.git
